# Generated by Django 4.2.2 on 2023-06-06 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='学校名')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.IntegerField(choices=[('小学校', ((1, '1年生'), (2, '2年生'), (3, '3年生'), (4, '4年生'), (5, '5年生'), (6, '6年生'))), ('中学校', ((7, '1年生'), (8, '2年生'), (9, '3年生'))), ('高校', ((10, '1年生'), (11, '2年生'), (12, '3年生'))), (13, '既卒')], verbose_name='学年')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.school', verbose_name='学校')),
                ('subjects', models.ManyToManyField(blank=True, to='lessons.subject', verbose_name='やる教科')),
            ],
            options={
                'verbose_name': '学年',
                'verbose_name_plural': '学年',
            },
        ),
    ]
