services:
  next:
    image: node:18.16.0-bullseye-slim
    command: sh -c "npm run dev"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
        - .env
    ports:
      - "3000:3000"

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      FRONTEND_URL: http://localhost:3000
      # POSTGRES_HOST: $POSTGRES_HOST
      # POSTGRES_USER: $POSTGRES_USER
      # POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    env_file: 
      - .env
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

volumes:
  node_modules:
  db-data:
